---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sainox/public_html/calistheteacademy.com/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -r * $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
